# Generated by Django 5.1.7 on 2025-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0019_alter_prismaendpoint_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopinfra',
            name='migration_sdwan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sopinfra',
            name='monitor_in_starting',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
