# Generated by Django 5.1.7 on 2025-06-04 11:27

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
        ('sop_infra', '0020_alter_sopinfra_migration_sdwan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SopMerakiDash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('api_url', models.URLField()),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Meraki dashboard',
                'verbose_name_plural': 'Meraki dashboards',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SopMerakiOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=50)),
                ('dash', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sop_infra.sopmerakidash')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Meraki organisation',
                'verbose_name_plural': 'Meraki organisations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SopMerakiNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=150)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sop_infra.sopmerakiorg')),
            ],
            options={
                'verbose_name': 'Meraki network',
                'verbose_name_plural': 'Meraki network',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='sopmerakiorg',
            constraint=models.UniqueConstraint(fields=('name', 'dash'), name='sop_infra_sopmerakiorg_unique_dash_org', violation_error_message='This dashboard already has an org with this name.'),
        ),
        migrations.AddConstraint(
            model_name='sopmerakinet',
            constraint=models.UniqueConstraint(fields=('name', 'org'), name='sop_infra_sopmerakinet_unique_net_dash', violation_error_message='This org already has an net with this name.'),
        ),
    ]
