# Generated by Django 5.1.7 on 2025-06-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
        ('sop_infra', '0021_sopmerakidash_sopmerakiorg_sopmerakinet_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sopmerakinet',
            name='sop_infra_sopmerakinet_unique_net_dash',
        ),
        migrations.RemoveConstraint(
            model_name='sopmerakiorg',
            name='sop_infra_sopmerakiorg_unique_dash_org',
        ),
        migrations.RenameField(
            model_name='sopmerakidash',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='sopmerakinet',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='sopmerakiorg',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='sopmerakidash',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakiorg',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sopmerakinet',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nets', to='sop_infra.sopmerakiorg'),
        ),
        migrations.AlterField(
            model_name='sopmerakiorg',
            name='dash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orgs', to='sop_infra.sopmerakidash'),
        ),
        migrations.AddConstraint(
            model_name='sopmerakinet',
            constraint=models.UniqueConstraint(fields=('nom', 'org'), name='sop_infra_sopmerakinet_unique_net_dash', violation_error_message='This org already has an net with this name.'),
        ),
        migrations.AddConstraint(
            model_name='sopmerakiorg',
            constraint=models.UniqueConstraint(fields=('nom', 'dash'), name='sop_infra_sopmerakiorg_unique_dash_org', violation_error_message='This dashboard already has an org with this name.'),
        ),
    ]
