# Generated by Django 5.1.7 on 2025-06-04 15:53

import django.utils.timezone
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0022_remove_sopmerakinet_sop_infra_sopmerakinet_unique_net_dash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakiorg',
            name='meraki_id',
            field=models.CharField(default=f"{uuid.uuid4}", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
