# Generated by Django 5.1.7 on 2025-06-04 16:29

import django.utils.timezone
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0023_sopmerakiorg_meraki_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakinet',
            name='meraki_id',
            field=models.CharField(default=f"{uuid.uuid4}", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
