# Generated by Django 5.1.7 on 2025-06-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0024_sopmerakinet_meraki_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakinet',
            name='bound_to_template',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakinet',
            name='meraki_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakinet',
            name='meraki_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
