# Generated by Django 5.1.7 on 2025-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0025_sopmerakinet_bound_to_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakiorg',
            name='meraki_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
