# Generated by Django 5.1.7 on 2025-06-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0026_sopmerakiorg_meraki_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopmerakinet',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nets', to='sop_infra.sopmerakiorg'),
        ),
        migrations.AlterField(
            model_name='sopmerakiorg',
            name='dash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='sop_infra.sopmerakidash'),
        ),
    ]
