# Generated by Django 5.1.7 on 2025-06-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0027_alter_sopmerakinet_org_alter_sopmerakiorg_dash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopmerakiorg',
            name='description',
        ),
    ]
