# Generated by Django 5.1.7 on 2025-06-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('sop_infra', '0028_remove_sopmerakiorg_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakinet',
            name='meraki_tags',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='sopmerakinet',
            name='ptypes',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='sopmerakinet',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meraki_nets', to='dcim.site'),
        ),
    ]
