# Generated by Django 5.1.7 on 2025-06-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0029_sopmerakinet_meraki_tags_sopmerakinet_ptypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopmerakinet',
            name='meraki_tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='sopmerakinet',
            name='ptypes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
