# Generated by Django 5.1.7 on 2025-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0030_alter_sopmerakinet_meraki_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakinet',
            name='timezone',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
