# Generated by Django 5.1.7 on 2025-06-12 12:19

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0031_sopmerakinet_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopmerakinet',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
    ]
