# Generated by Django 5.1.7 on 2025-06-12 22:57

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
        ('sop_infra', '0032_alter_sopmerakinet_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SopMerakiDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('nom', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=16, unique=True)),
                ('model', models.CharField(max_length=16)),
                ('mac', models.CharField(blank=True, max_length=20, null=True)),
                ('meraki_netid', models.CharField(max_length=150)),
                ('ptype', models.CharField(max_length=50)),
                ('meraki_tags', models.JSONField(blank=True, default=list, null=True)),
                ('meraki_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('meraki_details', models.JSONField(blank=True, default=list, null=True)),
                ('firmware', models.CharField(blank=True, max_length=50, null=True)),
                ('meraki_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sop_infra.sopmerakinet')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sop_infra.sopmerakiorg')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meraki_devices', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Meraki Device',
                'verbose_name_plural': 'Meraki Devices',
                'abstract': False,
            },
        ),
    ]
