# Generated by Django 5.1.7 on 2025-06-16 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('sop_infra', '0033_sopmerakidevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakidevice',
            name='netbox_dev_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meraki_devices', to='dcim.devicetype'),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='netbox_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meraki_devices', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='sopmerakidevice',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sop_infra.sopmerakiorg'),
        ),
    ]
