# Generated by Django 5.1.7 on 2025-06-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0034_sopmerakidevice_netbox_dev_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopmerakidevice',
            name='meraki_netid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
