# Generated by Django 5.2.2 on 2025-06-18 12:43

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('extras', '0128_tableconfig'),
        ('sop_infra', '0035_alter_sopmerakidevice_meraki_netid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrismaTunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('tunnel_name', models.CharField(max_length=150)),
                ('prisma_org_id', models.CharField(max_length=150)),
                ('psk', models.CharField(max_length=150)),
                ('local_id', models.CharField(max_length=150)),
                ('remote_id', models.CharField(max_length=150)),
                ('peer_ip', models.CharField(max_length=150)),
                ('sites', models.ManyToManyField(blank=True, related_name='prisma_tunnels', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Prisma Tunnel',
                'verbose_name_plural': 'Prisma Tunnels',
                'abstract': False,
            },
        ),
    ]
