# Generated by Django 5.2.2 on 2025-06-18 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0036_prismatunnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prismatunnel',
            name='sites',
        ),
        migrations.AddField(
            model_name='sopinfra',
            name='tunnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sop_infra.prismatunnel'),
        ),
    ]
