# Generated by Django 5.2.2 on 2025-06-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('extras', '0128_tableconfig'),
        ('sop_infra', '0037_remove_prismatunnel_sites_sopinfra_tunnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prismatunnel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='sopinfra',
            name='tunnel',
        ),
        migrations.RemoveConstraint(
            model_name='prismaendpoint',
            name='sop_infra_prismaendpoint_name_none',
        ),
        migrations.RemoveConstraint(
            model_name='prismaendpoint',
            name='sop_infra_prismaendpoint_slug_none',
        ),
        migrations.AddField(
            model_name='prismaendpoint',
            name='local_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prismaendpoint',
            name='peer_ip',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prismaendpoint',
            name='prisma_org_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prismaendpoint',
            name='psk',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prismaendpoint',
            name='remote_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sopinfra',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sop_infra.prismaendpoint'),
        ),
        migrations.AlterConstraint(
            model_name='sopinfra',
            name='sop_infra_sopinfra_unique_site',
            constraint=models.UniqueConstraint(fields=('site',), name='sop_infra_sopinfra_unique_site', violation_error_message="This site has already a 'SOP Infra'."),
        ),
        migrations.DeleteModel(
            name='PrismaTunnel',
        ),
    ]
