# Generated by Django 5.2.2 on 2025-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0038_remove_prismatunnel_tags_remove_sopinfra_tunnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopinfra',
            name='ad_direct_users_bc',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopinfra',
            name='est_cumulative_users_bc',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopinfra',
            name='wan_computed_users_bc',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
