# Generated by Django 5.2.3 on 2025-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0039_sopinfra_ad_direct_users_bc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sopinfra',
            old_name='ad_direct_users',
            new_name='ad_direct_users_wc',
        ),
        migrations.RenameField(
            model_name='sopinfra',
            old_name='est_cumulative_users',
            new_name='est_cumulative_users_wc',
        ),
        migrations.RenameField(
            model_name='sopinfra',
            old_name='wan_computed_users',
            new_name='wan_computed_users_wc',
        ),
        migrations.AddField(
            model_name='sopinfra',
            name='ad_direct_users_ext',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopinfra',
            name='ad_direct_users_nom',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopinfra',
            name='est_cumulative_users_ext',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopinfra',
            name='est_cumulative_users_nom',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
