# Generated by Django 5.2.3 on 2025-07-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0040_rename_ad_direct_users_sopinfra_ad_direct_users_wc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopinfra',
            name='site_mx_model',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
