# Generated by Django 5.2.3 on 2025-07-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0041_alter_sopinfra_site_mx_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopinfra',
            name='claim_net_mr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sop_infra.sopmerakinet'),
        ),
        migrations.AddField(
            model_name='sopinfra',
            name='claim_net_ms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sop_infra.sopmerakinet'),
        ),
        migrations.AddField(
            model_name='sopinfra',
            name='claim_net_mx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sop_infra.sopmerakinet'),
        ),
    ]
