# Generated by Django 5.2.3 on 2025-07-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('sop_infra', '0042_sopinfra_claim_net_mr_sopinfra_claim_net_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopinfra',
            name='criticity_stars',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='sopinfra',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='sopinfra',
            name='site_user_count',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sopinfra',
            name='wan_reco_bw',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
