# Generated by Django 5.2.3 on 2025-07-09 14:50

from django.db import migrations, models

def set_isilog_code(apps, schema_editor):
    sitemod = apps.get_model("dcim", "Site")
    for site in sitemod.objects.all():
        if site.sopinfra and site.region and site.tenant :
            site.sopinfra.site_isilog_code = f"{site.region.name}-{site.tenant.group.name}-{site.name}"


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0043_alter_sopinfra_criticity_stars_alter_sopinfra_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopinfra',
            name='site_isilog_code',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
        migrations.RunPython(set_isilog_code),
    ]
