# Generated by Django 5.2.3 on 2025-07-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0044_sopinfra_site_isilog_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopinfra',
            name='site_isilog_code',
        ),
    ]
