# Generated by Django 5.2.3 on 2025-07-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('sop_infra', '0045_remove_sopinfra_site_isilog_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopinfra',
            name='master_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.site'),
        ),
    ]
