# Generated by Django 5.2.3 on 2025-07-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0046_alter_sopinfra_master_site'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sopmerakinet',
            name='sop_infra_sopmerakinet_unique_net_dash',
        ),
    ]
