# Generated by Django 5.2.3 on 2025-07-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0047_remove_sopmerakinet_sop_infra_sopmerakinet_unique_net_dash'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopinfra',
            name='claim_net_mv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sop_infra.sopmerakinet'),
        ),
    ]
