# Generated by Django 5.2.3 on 2025-07-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0048_sopinfra_claim_net_mv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopinfra',
            name='claim_net_mv',
        ),
    ]
