# Generated by Django 5.2.3 on 2025-07-22 14:49

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    model = apps.get_model("sop_infra", "SopMerakiDevice")
    lst=model.objects.all().values('netbox_device').annotate(count=Count('netbox_device_id')).filter(count__gt=1).values_list('netbox_device', flat=True) 
    model.objects.filter(netbox_device_id__in=lst).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('sop_infra', '0050_sopmerakiswitchsettings_sopmerakiswitchstack_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name='sopmerakidevice',
            name='netbox_device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meraki_device', to='dcim.device'),
        ),
    ]
