# Generated by Django 5.2.3 on 2025-07-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0051_alter_sopmerakidevice_netbox_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sopmerakidevice',
            old_name='model',
            new_name='model_name',
        ),
    ]
