# Generated by Django 5.2.3 on 2025-07-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0052_rename_model_sopmerakidevice_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakidevice',
            name='cfg_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='lan_ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='meraki_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
