# Generated by Django 5.2.3 on 2025-07-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0053_sopmerakidevice_cfg_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakidevice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
