# Generated by Django 5.2.3 on 2025-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0054_sopmerakidevice_latitude_sopmerakidevice_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakiorg',
            name='meraki_api',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakiorg',
            name='meraki_cloud',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakiorg',
            name='meraki_licensing',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
