# Generated by Django 5.2.3 on 2025-08-05 12:45

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0129_fix_script_paths'),
        ('sop_infra', '0055_sopmerakiorg_meraki_api_sopmerakiorg_meraki_cloud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopdevicesetting',
            name='manage_in_netbox',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SopMerakiSwitchPortSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('port_id', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('port_enabled', models.BooleanField(default=False)),
                ('switchport_mode', models.CharField(max_length=20)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('voice_vlan', models.IntegerField(blank=True, null=True)),
                ('allowed_vlans', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('rstp_enabled', models.BooleanField(default=False)),
                ('stp_guard', models.CharField(default='disabled')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Meraki Switch Port Settings',
                'verbose_name_plural': 'Meraki Switch Ports Settings',
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SopSwitchPortTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('switchport_name', models.CharField(max_length=50)),
                ('switchport_enabled', models.BooleanField(default=False)),
                ('switchport_mode', models.CharField(max_length=20)),
                ('vlan_role_name', models.IntegerField(blank=True, null=True)),
                ('voice_vlan_role_name', models.IntegerField(blank=True, null=True)),
                ('allowed_vlan_group_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('rstp_enabled', models.BooleanField(default=False)),
                ('bpdu_guard', models.CharField(default='disabled')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'SOP Switch Port Template',
                'verbose_name_plural': 'SOP Switch Port Templates',
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
