# Generated by Django 5.2.3 on 2025-08-21 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('sop_infra', '0056_sopdevicesetting_manage_in_netbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopmerakidevice',
            name='custom_field_data',
        ),
        migrations.AddField(
            model_name='sopmerakiswitchstack',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meraki_switchstacks', to='dcim.site'),
        ),
    ]
