# Generated by Django 5.2.3 on 2025-08-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0057_remove_sopmerakidevice_custom_field_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopmerakiswitchstack',
            name='custom_field_data',
        ),
    ]
