# Generated by Django 6.0.5 on 2026-06-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0058_remove_sopmerakiswitchstack_custom_field_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sopinfra',
            old_name='criticity_stars',
            new_name='criticality_stars',
        ),
    ]
