# Generated by Django 6.0.5 on 2026-07-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0059_rename_criticity_stars_sopinfra_criticality_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakinet',
            name='appliance_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakinet',
            name='meraki_peers_reachability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
