# Generated by Django 6.0.5 on 2026-07-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0060_sopmerakinet_appliance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakinet',
            name='vpn_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
