# Generated by Django 6.0.5 on 2026-07-15 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0061_sopmerakinet_vpn_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakinet',
            name='exp_subnets_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakinet',
            name='last_stats_change',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
