# Generated by Django 6.0.5 on 2026-07-16 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0062_sopmerakinet_exp_subnets_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakidevice',
            name='last_reported_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='wan1ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='wan1status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='wan2ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='wan2status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakinet',
            name='last_uplinksstatuses_fetch',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakinet',
            name='primary_mx',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='net_where_primary', to='sop_infra.sopmerakidevice'),
        ),
        migrations.AddField(
            model_name='sopmerakinet',
            name='secondary_mx',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='net_where_secondary', to='sop_infra.sopmerakidevice'),
        ),
    ]
