# Generated by Django 6.0.5 on 2026-07-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0063_sopmerakidevice_last_reported_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopmerakinet',
            name='last_uplinksstatuses_fetch',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
