# Generated by Django 6.0.5 on 2026-07-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0064_alter_sopmerakinet_last_uplinksstatuses_fetch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopmerakinet',
            name='last_uplinksstatuses_fetch',
        ),
    ]
