# Generated by Django 6.0.5 on 2026-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0065_remove_sopmerakinet_last_uplinksstatuses_fetch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sopmerakiorg',
            options={'permissions': [('claim_devices', 'Claim devices to inventory')]},
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='eox_end_of_sale',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='eox_end_of_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='eox_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='license_expiration_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
