# Generated by Django 6.0.5 on 2026-08-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0065_remove_sopmerakinet_last_uplinksstatuses_fetch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sopinfra',
            options={'permissions': [('create_networks', 'Create Meraki networks'), ('refresh_networks', 'Refresh Meraki networks'), ('recompute_sizing', 'Recompute SOPINFRA sizing')]},
        ),
        migrations.AlterModelOptions(
            name='sopmerakidash',
            options={'permissions': [('refresh', 'Refresh from dashboard')]},
        ),
        migrations.AlterModelOptions(
            name='sopmerakidevice',
            options={'permissions': [('move', 'Move')]},
        ),
        migrations.AlterModelOptions(
            name='sopmerakinet',
            options={'permissions': [('refresh', 'Refresh from dashboard')]},
        ),
        migrations.AlterModelOptions(
            name='sopmerakiorg',
            options={'permissions': [('claim', 'Claim new devices'), ('refresh', 'Refresh from dashboard')]},
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='eox_end_of_sale',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='eox_end_of_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='eox_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='license_expiration_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
