# Generated by Django 6.0.5 on 2026-08-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0066_alter_sopinfra_options_alter_sopmerakidash_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sopmerakinet',
            options={'permissions': [('refresh', 'Refresh from dashboard'), ('move', 'Move')]},
        ),
    ]
