# Generated by Django 6.0.5 on 2026-08-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0066_alter_sopmerakiorg_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sopinfra',
            options={'permissions': [('claim_meraki_devices', 'Claim Meraki devices'), ('create_meraki_networks', 'Create Meraki networks'), ('refresh', 'Refresh Meraki networks'), ('recompute_sizing', 'Recompute SOPINFRA sizing')]},
        ),
        migrations.AlterModelOptions(
            name='sopmerakidevice',
            options={'permissions': [('move_meraki_devices', 'Move Meraki devices between Meraki Networks')]},
        ),
        migrations.AlterModelOptions(
            name='sopmerakiorg',
            options={'permissions': [('claim_meraki_devices', 'Claim devices to inventory')]},
        ),
    ]
