# Generated by Django 6.0.5 on 2026-08-13 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0067_alter_sopmerakinet_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopmerakidevice',
            name='meraki_network',
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='meraki_network_obj',
            field=models.ForeignObject(blank=True, from_fields=['meraki_netid'], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sop_infra.sopmerakinet', to_fields=['meraki_id']),
        ),
    ]
