# Generated by Django 6.0.5 on 2026-08-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0068_remove_sopmerakidevice_meraki_network_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sopmerakidevice',
            old_name='meraki_network_obj',
            new_name='meraki_network',
        ),
    ]
