# Generated by Django 6.0.5 on 2026-08-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0069_rename_meraki_network_obj_sopmerakidevice_meraki_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopmerakidevice',
            name='netbox_dev_type',
        ),
    ]
