# Generated by Django 6.0.5 on 2026-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0089_default_ordering_indexes'),
        ('sop_infra', '0070_remove_sopmerakidevice_netbox_dev_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakiorg',
            name='vpnexclude_ipadd',
            field=models.ManyToManyField(related_name='+', to='ipam.ipaddress'),
        ),
        migrations.AddField(
            model_name='sopmerakiorg',
            name='vpnexclude_prefix',
            field=models.ManyToManyField(related_name='+', to='ipam.prefix'),
        ),
    ]
