# Generated by Django 6.0.5 on 2026-08-20 17:07

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('ipam', '0089_default_ordering_indexes'),
        ('sop_infra', '0071_sopmerakiorg_vpnexclude_ipadd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopmerakiorg',
            name='vpnexclude_ipadd',
            field=models.ManyToManyField(blank=True, related_name='+', to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='sopmerakiorg',
            name='vpnexclude_prefix',
            field=models.ManyToManyField(blank=True, related_name='+', to='ipam.prefix'),
        ),
        migrations.CreateModel(
            name='SopSyslogServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('server_port', models.PositiveIntegerField(default=514, validators=[django.core.validators.MinValueValidator(1)])),
                ('enabled', models.BooleanField(default=True)),
                ('server_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Meraki Syslog Server',
                'verbose_name_plural': 'Meraki Syslog Server',
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='sopinfra',
            name='syslog_servers',
            field=models.ManyToManyField(blank=True, to='sop_infra.sopsyslogserver'),
        ),
    ]
