# Generated by Django 6.0.5 on 2026-08-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0072_alter_sopmerakiorg_vpnexclude_ipadd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopmerakiorg',
            name='syslog_servers',
            field=models.ManyToManyField(blank=True, related_name='meraki_orgs', to='sop_infra.sopsyslogserver'),
        ),
    ]
