# Generated by Django 6.0.5 on 2026-08-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0073_sopmerakiorg_syslog_servers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sopmerakidevice',
            options={'permissions': [('move', 'Move'), ('refresh', 'Refresh')]},
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='ddns_hostnames',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='wan1',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sopmerakidevice',
            name='wan2',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
