# Generated by Django 6.0.8 on 2026-09-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sop_infra", "0073_sopmerakiorg_syslog_servers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sopmerakidevice",
            name="meraki_network",
            field=models.ForeignObject(
                blank=True,
                from_fields=("meraki_netid",),
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="devices",
                to="sop_infra.sopmerakinet",
                to_fields=("meraki_id",),
            ),
        ),
    ]
